export default {
  //公共配置
  company_en: "CISK",
  company: "昆山加拿大国际学校国内艺术幼儿部",
  address: "地址：中国江苏省昆山市祖冲之路1799号",
  phone: "电话：15358838850",
  tel: "座机：0512-57606969",
  copyright: "2020 CISK.Allrights reserved.苏ICP备12051615号",
  more: "查看更多",
  detail: "了解详情",
  pageHeader: "您的当前位置：",
  preArticle: "上一篇：",
  nextArticle: "下一篇：",
  back: "返回列表",
  none: "无",
  menu: [
    {
      index: 0,
      name: "首页",
      path: "/",
      biaoqian: [{ name: "首页", path: "/" }],
    },
    {
      index: 1,
      name: "走进幼儿部",
      path: "/about",
      biaoqian: [{ name: "走进幼儿部", path: "/about" }],
    },
    {
      index: 2,
      name: "教师风采",
      path: "/jsfclist",
      biaoqian: [{ name: "教师风采", path: "/jsfclist" }],
    },
    {
      index: 3,
      name: "教学教研",
      path: "/jxjylist",
      query: { tab: "教师成长" },
      biaoqian: [
        { name: "教师成长", path: "/jxjylist", query: { tab: "教师成长" } },
        { name: "教研信息", path: "/jxjylist", query: { tab: "教研信息" } },
        { name: "教计信息", path: "/jxjylist", query: { tab: "教计信息" } },
      ],
    },
    {
      index: 4,
      name: "幼儿保健",
      path: "/yebjlist",
      biaoqian: [{ name: "幼儿保健", path: "/yebjlist" }],
    },
    {
      index: 5,
      name: "新闻动态",
      path: "/news",
      biaoqian: [{ name: "新闻动态", path: "/news" }],
    },
    {
      index: 6,
      name: "家园互动",
      path: "/jyhd",
      query: { tab: "家园互动" },
      biaoqian: [
        { name: "家园互动", path: "/jyhd", query: { tab: "家园互动" } },
        { name: "活动花絮", path: "/jyhd", query: { tab: "活动花絮" } },
      ],
    },
    {
      index: 7,
      name: "安全科普",
      path: "/aqkplist",
      biaoqian: [{ name: "安全科普", path: "/aqkplist" }],
    },
    {
      index: 8,
      name: "艺术空间",
      path: "/yskjlist",
      biaoqian: [{ name: "艺术空间", path: "/yskjlist" }],
    },
    {
      index: 9,
      name: "招生说明",
      path: "/zssm",
      biaoqian: [{ name: "招生说明", path: "/zssm" }],
    },
    {
      index: 10,
      name: "联系我们",
      path: "/lxwm",
      biaoqian: [{ name: "联系我们", path: "/lxwm" }],
    },
  ],
  //首页
  home: {
    sectionList: [
      "走进幼儿部",
      "校园掠影",
      "一周食谱",
      "新闻动态",
      "艺术空间",
      "每周之星",
      "师生比",
    ],
    ablist: [
      { imgPath: require("../assets/home/a1.png"), name: "有爱的教育活动" },
      { imgPath: require("../assets/home/a2.png"), name: "丰富的课外活动" },
      { imgPath: require("../assets/home/a3.png"), name: "全程保姆式服务" },
      { imgPath: require("../assets/home/a4.png"), name: "绘画，钢琴，舞蹈等" },
      { imgPath: require("../assets/home/a5.png"), name: "出色的学习氛围" },
    ],
    xyly: [
      { imgPath: require("../assets/home/x.jpg"), name: "攀爬小桥" },
      { imgPath: require("../assets/home/x1.jpg"), name: "玩水区" },
      { imgPath: require("../assets/home/x2.jpg"), name: "校园掠影" },
      { imgPath: require("../assets/home/x3.jpg"), name: "沙池" },
    ],
  },
  //走进幼儿园
  about: {},
};
