export default {
  company_en: "CISK",
  company: "CISK",
  more: "MORE",
  address: "address:中国江苏省昆山市祖冲之路1799号",
  phone: "phone:15358838850",
  tel: "tel:0512-57606969",
  copyright: "2020 CISK.Allrights reserved.苏ICP备12051615号",
  pageHeader: "you current location:",
  menu: [
    { index: 0, name: "main" },
    { index: 1, name: "into" },
    { index: 2, name: "teacher" },
    { index: 3, name: "tach" },
    { index: 4, name: "baojian" },
    { index: 5, name: "xinwei" },
    { index: 6, name: "jiayuan" },
    { index: 7, name: "anquan" },
    { index: 8, name: "yishu" },
    { index: 9, name: "zhaosheng" },
    { index: 10, name: "lianxi" },
  ],
  home: {},
};
